# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.FloatField(default=0)),
                ('author', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=255)),
                ('dcount', models.IntegerField(default=0)),
                ('lcount', models.IntegerField(default=0)),
                ('dlcount', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='uploaded_files/')),
            ],
        ),
    ]
