# Generated by Django 2.0 on 2017-12-12 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('dcount', models.IntegerField(default=0)),
                ('lcount', models.IntegerField(default=0)),
                ('dlcount', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('size', models.FloatField(default=0.0)),
                ('size_postfix', models.CharField(blank=True, max_length=2)),
                ('upload_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
