# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171218_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
